name: My CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # Specifies the runner OS (you can choose a different one)

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2 # Checks out the repository's code

    - name: Run make command
      run: make hello
